### ISSUE TITLE
Use packages' names started with lower-case letters

### ISSUE THREAD

**Issue by starsasumi** [anqitong/LangageDessinVectoriel#12]
It would be more clear to start a package's name with lower-case letters, like `fr.emn.model`.

**Comment by starsasumi** [comment]
This is solved in PR #17

**Comment by anqitong** [comment]
Aren't the current package names all right?

**Comment by starsasumi** [comment]
@anqitong Yep, you solved all 👍. I assigned you to this because you are the one solved it.

**Comment by anqitong** [comment]
So can I merge now?

2015-10-23 12:07 GMT+02:00 SHI Xiaxing notifications@github.com:

**Comment by starsasumi** [comment]
I think so, it's clear all thing's right

**Comment by Thomas-dot-G** [comment]
Nope, not yet, but that has to be discussed on the PR rather than on the issue.

**Comment by Thomas-dot-G** [comment]
#18
