### ISSUE TITLE
Fill Method to write SVG code

### ISSUE THREAD

**Issue by anqitong** [anqitong/LangageDessinVectoriel#15]
Methods toString() creating svg code.
(toString in the Shapes class)

**Comment by Thomas-dot-G** [comment]
Why referencing that PR ?

**Comment by anqitong** [comment]
Where?

**Comment by starsasumi** [comment]
@anqitong I think he meant the `#14` in your original post

**Comment by Thomas-dot-G** [comment]
Yes, and now, this issue is referencing itself. Not sure it is useful...

**Comment by Thomas-dot-G** [comment]
Has to wait for #23 first
