### ISSUE TITLE
Package structure

### ISSUE THREAD

**Issue by anqitong** [anqitong/LangageDessinVectoriel#16]
#16

Is it okay if I add a package "test"? So the stucture will be : 
src
- main : - View
          - Model
          - Controller
- test

**Comment by Thomas-dot-G** [comment]
Yes but later, it's not important for the first sprint.
Just do an issue, it will then be done later

**Comment by starsasumi** [comment]
This is solved in PR #17

**Comment by Thomas-dot-G** [comment]
In #22 actually
