### ISSUE TITLE
Specify the language

### ISSUE THREAD

**Issue by Thomas-dot-G** [anqitong/LangageDessinVectoriel#19]
We have to specify the language that one's has to use in the main function to create something.
Language we have to describe in a doc, and that will be implemented in the code

```
Il doit être possible de déclarer des variables avec l'un des types puis de modifier leur valeur. Enfin, pour contrôler l'exécution des instructions, on doit disposer d'opérateurs de contrôle, tels que ceux qui suivent.

Séquence
Cet opérateur permet d'exécuter une première instruction, puis une seconde.

Alternative
Cet opérateur permet de choisir des instructions à exécuter suivant une condition booléenne. Il correspond à l'instruction classique if … then … else ….

Boucle
Cet opérateur permet de répéter un certain nombre de fois des instructions. Le nombre peut être fixé a priori (for) ou déterminé a posteriori par une condition (boucles while).
```

**Comment by Thomas-dot-G** [comment]
For the description, suggestions:
Software that ask if the user want to do that, and ask him to chose between stuff, or
Create a language and the user has to give a String and the software will analyse it , or
The user give a succession of instruction and the software will do it ?

**Comment by Thomas-dot-G** [comment]
Then, with a method describe above:
We need for a file: A name, an optional description, some shapes, and that is all ?
Maybe the name of the author

**Comment by anqitong** [comment]
The language is Java itself. So I would suggest that the user gives a series of instructions in Java.

**Comment by starsasumi** [comment]
I prefer to use java codes as this script language. Writing a compiler (or even a lexer) is just too much works for us.

**Comment by starsasumi** [comment]
And using java codes as script language, the commands are just our APIs. We only need to provide users an interface for our APIs, and java compiler would do all the checking jobs for us.

**Comment by anqitong** [comment]
I completely agree with Xiaxing. No need to define another language because it will be too much work (parser, lexer ...). And Hervé Grall told us he also suggested that we use Java as "langage embarqué" instead of creating a new language.

**Comment by Thomas-dot-G** [comment]
That is not what I mean for a language
I mean, does the user will write in the main: Figure c = new Circle(0,0,0,green); c.display();
Or something more like: just write in a string: "Figure: Circle; Center: 0,0; Color: green"
Or the user will be asked in the console to write the shape, the user will enter it, then the software will ask the user to enter the center of it...

So I mean what is the type of language used between the human and the software, not the one used with parser which had already been discussed during the first meeting.

All the one above (which are not exhaustive) does not need compiler or parser, at least not real ones are the structure will be really simple.

**Comment by Thomas-dot-G** [comment]
```
Il doit être possible de déclarer des variables avec l'un des types puis de modifier leur valeur. Enfin, pour contrôler l'exécution des instructions, on doit disposer d'opérateurs de contrôle, tels que ceux qui suivent.

Séquence
Cet opérateur permet d'exécuter une première instruction, puis une seconde.

Alternative
Cet opérateur permet de choisir des instructions à exécuter suivant une condition booléenne. Il correspond à l'instruction classique if … then … else ….

Boucle
Cet opérateur permet de répéter un certain nombre de fois des instructions. Le nombre peut être fixé a priori (for) ou déterminé a posteriori par une condition (boucles while).
```

But we can leave it for the moment if you want

**Comment by starsasumi** [comment]
I was imagining APIs like this:

```
class MyTask implements DrawingTask {
    public void draw(Painter p) {
        p.setDestination(pathToSaveSVG);

        p.setPencil(...);
        p.circle(...);
        p.line(...);

        p.setPencil(...);
        p.path(...);
    }
}
```

**Comment by Thomas-dot-G** [comment]
This actually looks good for me. Simple but effective.

**Comment by anqitong** [comment]
It also looks good for me.

**Comment by starsasumi** [comment]
I found a post for running java source codes in runtime: 

http://www.beyondlinux.com/2011/07/20/3-steps-to-dynamically-compile-instantiate-and-run-a-java-class/

We could try this.

**Comment by Thomas-dot-G** [comment]
Why would we use that ?

**Comment by anqitong** [comment]
I don't think we need it

**Comment by starsasumi** [comment]
Or we ask the user to modify the script source code and the user him/herself compile the project again?

**Comment by Thomas-dot-G** [comment]
That will be the case I thing according to M Grall

**Comment by starsasumi** [comment]
That's great!

**Comment by starsasumi** [comment]
@anqitong , @Thomas-dot-G 
Should we work on this now? Or using shapes objects in a main function is already our "language" ?

**Comment by Thomas-dot-G** [comment]
I think that will be the user interface that will be the "language" as well as the things we already have in the main

**Comment by anqitong** [comment]
Hey! I haven't thought of it!! Indeed you're right, it does correspond to the description by the teacher!

**Comment by starsasumi** [comment]
You mean, the UI is the language? Huh, we could see it in this way is theory. But for the prof ... I am not sure. And the language should be able to do `for`, `if`, etc.

**Comment by Thomas-dot-G** [comment]
Yeah, that is why we have the basic java code for that^^
