### ISSUE TITLE
Add ShapeXMLFactory?

### ISSUE THREAD

**Issue by anqitong** [anqitong/LangageDessinVectoriel#43]
As ShapeFactory, usesShapeName to create for example EllipseXML, LineXML, ... etc

**Comment by Thomas-dot-G** [comment]
And if simplify the creation of object for the user.
I mean, the ShapeFactory should also create the shapes in general

**Comment by starsasumi** [comment]
We already have a "factory" for ShapeStates, method 'getShapeState(Shape shape)' in interface `Presentation`. And all these classes have nothing to do with user interfaces

**Comment by Thomas-dot-G** [comment]
yes, so we can put a user interface (even in the consol) that just create everything when a circle is added by example.
So for example, the method addShape for Drawingxml will just take shapes and also create the XMLShapes at the same time.
