### ISSUE TITLE
Create a new way to visualize the drawing

### ISSUE THREAD

**Issue by Thomas-dot-G** [anqitong/LangageDessinVectoriel#50]
ie create a second implementation

**Comment by starsasumi** [comment]
I propose that we integrate the second presentation to our user interface. Therefore, after user created a drawing script, our software can display it as the default presentation. Then, user can chose to export it as SVG, and that's  the use case for SVG presentation.

**Comment by Thomas-dot-G** [comment]
Not really sure what you mean:
So we create a default display and then the user can choose to change ?
And so SVG is not the default option ?

**Comment by starsasumi** [comment]
What I mean is that we create the second presentation as a presentation in Java Swing. So like other drawing applications, user create image and he/she can view the result in application (This is the presentation we have not created). And he/she can also save/export it as a SVG file. In a word, one presentation for viewing, one presentation for export.

Like this (replace PDF with SVG)
<img width="1322" alt="screen shot 2015-11-02 at 18 07 28" src="https://cloud.githubusercontent.com/assets/2586228/10888565/4371c9ae-818d-11e5-8483-f3b3db5a4eba.png">

**Comment by Thomas-dot-G** [comment]
I Agree !

**Comment by anqitong** [comment]
Also agree

**Comment by starsasumi** [comment]
I think I could work on this
