### ISSUE TITLE
Add option to transform a svg file into a java object

### ISSUE THREAD

**Issue by Thomas-dot-G** [anqitong/LangageDessinVectoriel#58]

**Comment by starsasumi** [comment]
To implement this, I think it's fare for us to add a XML library?

**Comment by anqitong** [comment]
I'm not sure it is authroized, but we can send him an email to make sure we can. Because in the subject it is not really written : http://www.grall.name/teaching/softwareArchitecture/2016/project_vectorGraphics.html
Would you like me to send an email?

**Comment by starsasumi** [comment]
Let me explore the official xml support in Java SDK first. Maybe it's enough to solve this with the SDK 🤔

**Comment by Thomas-dot-G** [comment]
Even if not robust, it would not be difficult to do it ourself. If needed I can do it !

**Comment by starsasumi** [comment]
I believed there are some basic xml support in Java SDK that we could use. @Thomas-dot-G you can find them in 'javax.xml' package

**Comment by Thomas-dot-G** [comment]
Maybe, but that means you would rather use some support than just do it ourselves ?

**Comment by anqitong** [comment]
If it is authorized, it would be mre efficient.

**Comment by Thomas-dot-G** [comment]
~~JAXB?~~

**Comment by starsasumi** [comment]
We use `javax.xml` to transform pure text to xml elements and than analyze them and create the java object we want. Because text analyzing is too heavy for this project. (a robust [lexical analyzer](https://github.com/starsasumi/JavaLexicalAnalyzer) itself would already enough to be a school project)

**Comment by starsasumi** [comment]
I think I would work on this this week.
