### ISSUE TITLE
Idea for composite pattern

### ISSUE THREAD

**Issue by anqitong** [anqitong/LangageDessinVectoriel#59]
Let's see the canvas or the SVG file as a paper filled with Shapes. 
Interface : Liste<Shape>
Classes : FilledArea = Cons(Shape head , Liste<Shape> rest)
              Circle, Ellipse, ... etc implements Shape / add EmptyTile implements Shape too

And then, in svg file, we can have as attribute : 
private Liste<Shape> listShapes;

**Comment by anqitong** [comment]
Rectification : we can also use generic names such as Liste<E>, Cons<E> and TerminalElement<E>, so that we could reuse this composite pattern somewhere else.

**Comment by starsasumi** [comment]
We can add a method to get this list. But for the pattern and other generic interfaces, I don't know much yet.

**Comment by anqitong** [comment]
In fact I was wondering if it is too late, because now if we chang something, almost everything has to be changed

**Comment by Thomas-dot-G** [comment]
something composite can be added, and some modif can be easealy done

**Comment by starsasumi** [comment]
For me, I think we should focus on finishing the gui first I think.

**Comment by anqitong** [comment]
The gui is done, can you test it? #63

**Comment by starsasumi** [comment]
@anqitong It already works? I will test it later. Could you also test #67 #66 for me?
