### ISSUE TITLE
Update read me and Wiki

### ISSUE THREAD

**Issue by Thomas-dot-G** [anqitong/LangageDessinVectoriel#69]
That will be the final task

**Comment by starsasumi** [comment]
I put the parts of README.md that I wrote and removed from the #67 to the next post as a backup. Feel free to reuse it ;)

**Comment by starsasumi** [comment]
# LangageDessinVectoriel

This project aims to create vector graphics through the command of user, and graphics that are created could be showed in a java frame and saved as a SVG file.

The subject of the subject is described [here](http://www.grall.name/teaching/softwareArchitecture/2016/project_vectorGraphics.html) (in French)

## About the software:

Once the project is retrieved, you can use it to create graphics. With this project, you have two ways to draw an image. Firstly, using the **GUI** to draw, which is easy to use; or you can use a **drawing language** based on Java, which is less intuitive but you will gain more control from it.

In the package src/view, you will find 3 classes needed:
- `view.GUI`: This is the entrance for our GUI.
- `view.Painting`: Here is the "drawing language" that we defined. It is a script that you could modify to tell the software what it should draw.
- `view.Draw`: // **TODO**.

## Using the GUI

// **TODO**

## Using the drawing language

The drawing language is clear and simple. And it's basically a class that calls our well defined APIs. Here is an example: 

```
public class Painting implements DrawingTask {

    @Override
    public void draw(Painter p) {
        p.setName("Painting with language");
        p.setCanvasSize(600, 600);

        p.stroke(1, Color.blue);
        p.fill(Color.red);
        p.circle(30, 30, 30);

        p.stroke(2, Color.darkGray);
        p.ellipse(100, 30, 40, 20);     }
}
```

As you can see, all drawing tasks are finished by calling methods in the given object `p` in the `void draw(Painter p)` method.

### Name & size:

To create a vector graphics, we need to call `p.setName` and `p.setCanvasSize` to define it's name and size. But it is not required to do this before calling other APIs. These two methods could be called at anytime. If they are not be called, a default setting would be used.

### Stroke & filling color:

You'll then need to decide the stroke and the filling color that would be used by calling these methods:
- `p.stroke(int width, Color strokeColor);`
- `p.fill(Color fillColor);`

These settings would be used as long as you do not change them. So in the example, both the circle and the ellipse are filled with red color that defined the line 9: `p.fill(Color.red);`.

### Shapes & text:

Here is all methods in `p` that you can draw: 

```
void circle(int x, int y, int r);
void ellipse(int x, int y, int rx, int ry);
void line(int x1, int y1, int x2, int y2);
void path(LineType type, int[] xs, int[] ys);
void polygone(int[] xs, int[] ys);
void polyline(int[] xs, int[] ys);
void rectangle(int x, int y, int width, int height);
void text(int x, int y, String text);
```

### Get result

After finishing writing codes in the `Painting` object, you can get the result by running it's `main` method. The SVG file is saved in `files/` with the name of the painting.

**Comment by Thomas-dot-G** [comment]
Great, for the view.Draw at the beginning, it it the same thing as last time, so we can just say what we said on the read me that is now displayed

**Comment by anqitong** [comment]
Using the GUI

The GUI is composed of models in _model_ package, controllers in _controller/guiController_ and the user interface in _view_.

To launch the gui, you need to run the _view/GUI.java_ class.
Once the gui is launched, you will have to use the text fields to create shapes.

Pencil : 

In the left panel, you have the pencil section : you can enter values for pencil thickness and for the pencil color. The inputs are the RGB components. For example, you will fill _255, 0, 0_ for the color RED.
The default color of the pencil is black.

Shapes : 

Under the pencil section, you will find radio buttons for the different shapes you want draw. Click on them and the input text fields will appear. 

Fill color : 

You can choose to fill the shapes when possible. The default color is white.

At the bottom of the left panel, you can add the shape to the list of shapes.

Text area :

The text area is in the right panel. Once you added your shapes, the corresponding xml will be displayed in it. 

Run the AWT : 

You can run the AWT preview before you save the image. Once you added your shapes, you can click on this button under the text area and see how it looks like.

Save the drawing : 

Add the bottom of the right panel you will see a text field to enter the name you want for the svg file. Once you completed it, you can click on the save button and the svg file will be saved in _files_, and also opened.

**Comment by anqitong** [comment]
@starsasumi : I added the "Using the GUI" part, can you update the README?

**Comment by Thomas-dot-G** [comment]
Actually the PR for the ReadMe has not been created yet

**Comment by Thomas-dot-G** [comment]
If needed I can do it

**Comment by anqitong** [comment]
yes please

**Comment by anqitong** [comment]
I created the branch readme_gui with the edited README but when I want to create the pull request it does not let me

**Comment by anqitong** [comment]
The readme in the branch readme_gui is updated : i added the using gui section

**Comment by Thomas-dot-G** [comment]
What ? (I will do it if you want)

**Comment by anqitong** [comment]
yes
